In [7]:
import numpy as np
from numpy import genfromtxt
my_data = genfromtxt("C:\\Users\\ridva\\OneDrive\\Masaüstü\\Notes\\B47-DS-TR-main\\06-Python Libraries\\Numpy Capstone Projects\\datasets\\transfusion.data", delimiter = ",")
my_data

array([[     nan,      nan,      nan,      nan,      nan],
       [2.00e+00, 5.00e+01, 1.25e+04, 9.80e+01, 1.00e+00],
       [0.00e+00, 1.30e+01, 3.25e+03, 2.80e+01, 1.00e+00],
       ...,
       [2.30e+01, 3.00e+00, 7.50e+02, 6.20e+01, 0.00e+00],
       [3.90e+01, 1.00e+00, 2.50e+02, 3.90e+01, 0.00e+00],
       [7.20e+01, 1.00e+00, 2.50e+02, 7.20e+01, 0.00e+00]])

In [8]:
type(my_data)

numpy.ndarray

In [10]:
my_data.ndim

2

In [11]:
my_data[0]

array([nan, nan, nan, nan, nan])

In [12]:
my_data = np.delete(my_data, 0, 0)

In [13]:
my_data 

array([[2.00e+00, 5.00e+01, 1.25e+04, 9.80e+01, 1.00e+00],
       [0.00e+00, 1.30e+01, 3.25e+03, 2.80e+01, 1.00e+00],
       [1.00e+00, 1.60e+01, 4.00e+03, 3.50e+01, 1.00e+00],
       ...,
       [2.30e+01, 3.00e+00, 7.50e+02, 6.20e+01, 0.00e+00],
       [3.90e+01, 1.00e+00, 2.50e+02, 3.90e+01, 0.00e+00],
       [7.20e+01, 1.00e+00, 2.50e+02, 7.20e+01, 0.00e+00]])

In [14]:
my_data.shape

(748, 5)

In [15]:
my_data.size

3740

In [16]:
my_data.dtype

dtype('float64')

In [17]:
my_data.itemsize

8

In [20]:
zero = np.zeros((2,5))
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
one = np.ones((2,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
thirtyeight = np.full((2,5), 38)
thirtyeight

array([[38, 38, 38, 38, 38],
       [38, 38, 38, 38, 38]])

In [23]:
eye = np.eye(5)
eye

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
random = np.random.random((2,5))
random

array([[0.12439198, 0.66067301, 0.97314655, 0.66586089, 0.95078716],
       [0.13013439, 0.64894362, 0.46671768, 0.81622303, 0.39357032]])

In [25]:
linsp = np.linspace(1,10,10).reshape((2,5))
linsp

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [26]:
linsp = np.sqrt(linsp)
linsp

array([[1.        , 1.41421356, 1.73205081, 2.        , 2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766]])

In [27]:
random = random**2
random

array([[0.01547336, 0.43648882, 0.94701422, 0.44337073, 0.90399622],
       [0.01693496, 0.42112782, 0.2178254 , 0.66622003, 0.1548976 ]])

In [28]:
sum = linsp + random
sum

array([[1.01547336, 1.85070239, 2.67906502, 2.44337073, 3.1400642 ],
       [2.4664247 , 3.06687913, 3.04625252, 3.66622003, 3.31717526]])

In [29]:
divide = one / zero
divide

<ipython-input-29-9ae30e9b7fb1>:1: RuntimeWarning: divide by zero encountered in true_divide
  divide = one / zero


array([[inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [30]:
subtraction= one-zero
subtraction

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
division=subtraction/sum
division

array([[0.98476241, 0.54033539, 0.37326455, 0.40927068, 0.31846483],
       [0.40544518, 0.32606437, 0.32827219, 0.2727605 , 0.30146131]])

In [35]:
eproduct=sum*division
eproduct

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
mproduct=eproduct@eye
mproduct

array([[1.01547336, 1.85070239, 2.67906502, 2.44337073, 3.1400642 ],
       [2.4664247 , 3.06687913, 3.04625252, 3.66622003, 3.31717526]])

In [39]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
a > 3

array([[False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [41]:
a[a>3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [42]:
a[a>3] = 0
a

array([[1, 2, 3, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
stc = np.stack((a, mproduct), axis = 1)
stc

array([[[1.        , 2.        , 3.        , 0.        , 0.        ],
        [1.01547336, 1.85070239, 2.67906502, 2.44337073, 3.1400642 ]],

       [[0.        , 0.        , 0.        , 0.        , 0.        ],
        [2.4664247 , 3.06687913, 3.04625252, 3.66622003, 3.31717526]]])

In [45]:
updated = stc[:, 0:1]
updated

array([[[1., 2., 3., 0., 0.]],

       [[0., 0., 0., 0., 0.]]])

In [46]:
updated = updated.reshape(2,5)
updated.ndim

2

In [47]:
data = np.concatenate([my_data, updated])
data

array([[2.00e+00, 5.00e+01, 1.25e+04, 9.80e+01, 1.00e+00],
       [0.00e+00, 1.30e+01, 3.25e+03, 2.80e+01, 1.00e+00],
       [1.00e+00, 1.60e+01, 4.00e+03, 3.50e+01, 1.00e+00],
       ...,
       [7.20e+01, 1.00e+00, 2.50e+02, 7.20e+01, 0.00e+00],
       [1.00e+00, 2.00e+00, 3.00e+00, 0.00e+00, 0.00e+00],
       [0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00, 0.00e+00]])

In [48]:
data.sum(axis=0)

array([7.112000e+03, 4.127000e+03, 1.031253e+06, 2.564300e+04,
       1.780000e+02])

In [49]:
data.sum(axis=1)

array([1.2651e+04, 3.2920e+03, 4.0530e+03, 5.0680e+03, 6.1020e+03,
       1.0120e+03, 1.7740e+03, 3.0480e+03, 2.2840e+03, 1.1650e+04,
       5.8350e+03, 7.5700e+02, 2.5410e+03, 3.3110e+03, 1.5240e+03,
       1.2690e+03, 3.5650e+03, 3.8170e+03, 1.5240e+03, 7.6000e+02,
       7.6000e+02, 2.7930e+03, 1.5250e+03, 1.5250e+03, 2.2840e+03,
       3.5580e+03, 1.5240e+03, 3.0510e+03, 1.2710e+03, 2.0330e+03,
       3.5730e+03, 2.5430e+03, 2.5430e+03, 2.2900e+03, 4.0820e+03,
       2.0390e+03, 3.0620e+03, 1.5270e+03, 3.5740e+03, 1.7840e+03,
       3.3190e+03, 1.2730e+03, 1.2740e+03, 1.2730e+03, 5.0940e+03,
       2.2920e+03, 2.2970e+03, 5.0600e+02, 5.0600e+02, 5.0600e+02,
       2.8090e+03, 2.8100e+03, 1.5300e+03, 3.0660e+03, 1.2740e+03,
       4.8430e+03, 2.0390e+03, 1.7880e+03, 4.0990e+03, 1.5300e+03,
       1.7880e+03, 2.0460e+03, 2.5610e+03, 1.2760e+03, 7.6500e+02,
       4.0930e+03, 1.0210e+03, 5.0600e+02, 1.7860e+03, 2.3110e+03,
       1.0220e+03, 1.0220e+03, 4.3430e+03, 5.0800e+02, 5.0900e

In [51]:
data.max(axis=1)

array([1.250e+04, 3.250e+03, 4.000e+03, 5.000e+03, 6.000e+03, 1.000e+03,
       1.750e+03, 3.000e+03, 2.250e+03, 1.150e+04, 5.750e+03, 7.500e+02,
       2.500e+03, 3.250e+03, 1.500e+03, 1.250e+03, 3.500e+03, 3.750e+03,
       1.500e+03, 7.500e+02, 7.500e+02, 2.750e+03, 1.500e+03, 1.500e+03,
       2.250e+03, 3.500e+03, 1.500e+03, 3.000e+03, 1.250e+03, 2.000e+03,
       3.500e+03, 2.500e+03, 2.500e+03, 2.250e+03, 4.000e+03, 2.000e+03,
       3.000e+03, 1.500e+03, 3.500e+03, 1.750e+03, 3.250e+03, 1.250e+03,
       1.250e+03, 1.250e+03, 5.000e+03, 2.250e+03, 2.250e+03, 5.000e+02,
       5.000e+02, 5.000e+02, 2.750e+03, 2.750e+03, 1.500e+03, 3.000e+03,
       1.250e+03, 4.750e+03, 2.000e+03, 1.750e+03, 4.000e+03, 1.500e+03,
       1.750e+03, 2.000e+03, 2.500e+03, 1.250e+03, 7.500e+02, 4.000e+03,
       1.000e+03, 5.000e+02, 1.750e+03, 2.250e+03, 1.000e+03, 1.000e+03,
       4.250e+03, 5.000e+02, 5.000e+02, 5.000e+02, 1.000e+03, 5.000e+02,
       5.000e+02, 5.000e+02, 1.500e+03, 1.000e+03, 

In [52]:
data.max(axis=0)

array([7.40e+01, 5.00e+01, 1.25e+04, 9.80e+01, 1.00e+00])

In [53]:
data.min(axis=0)

array([0., 0., 0., 0., 0.])

In [54]:
data.min(axis=1)

array([1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1.,
       1., 1., 1., 1., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 1., 0., 1., 1., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 1., 0., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       1., 1., 0., 1., 1.

In [55]:
np.argmax(data)

2

In [56]:
np.argmin(data)

5

In [57]:
datat = data.T
datat

array([[2.00e+00, 0.00e+00, 1.00e+00, ..., 7.20e+01, 1.00e+00, 0.00e+00],
       [5.00e+01, 1.30e+01, 1.60e+01, ..., 1.00e+00, 2.00e+00, 0.00e+00],
       [1.25e+04, 3.25e+03, 4.00e+03, ..., 2.50e+02, 3.00e+00, 0.00e+00],
       [9.80e+01, 2.80e+01, 3.50e+01, ..., 7.20e+01, 0.00e+00, 0.00e+00],
       [1.00e+00, 1.00e+00, 1.00e+00, ..., 0.00e+00, 0.00e+00, 0.00e+00]])